### ISSUE TITLE
Fix PHPStan failures

### ISSUE THREAD

**Issue by colinodell** [thephpleague/config#23]
PHPStan is currently failing due to these errors:

> PHPStan: src/Configuration.php#L120 Dead catch - Dflydev\DotAccessData\Exception\MissingPathException is never thrown in the try block.
>
> PHPStan: src/Configuration.php#L193 Parameter 1 $data of method Dflydev\DotAccessData\Data::import() expects array<string, mixed>, array given.

Let's fix these to make the pipelines pass.

**Comment by praem90** [comment]
Can I work on this @colinodell ?
