### ISSUE TITLE
Please add supporting version for PHP 8.1/8.2/8.3/8.4 for latest version

### ISSUE THREAD

**Issue by pvsaintpe** [thephpleague/config#27]
"php": "...|^8.1|^8.2|^8.3|^8.4"

**Comment by froschdesign** [comment]
@pvsaintpe 
Is already in place: https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by colinodell** [comment]
This library already supports all PHP 8.x versions as @froschdesign points out.  I've updated CI (in #28) to confirm this is installable on those versions and that all tests pass.
